#ifndef CC_PROGRAMS_EXAMPLES_EXAMPLE3_MAXVALUE_MAXVALUE
#define CC_PROGRAMS_EXAMPLES_EXAMPLE3_MAXVALUE_MAXVALUE

#include <iostream>
#include <vector> 

int maxValue(std::vector<int> &input);

#endif /* CC_PROGRAMS_EXAMPLES_EXAMPLE3_MAXVALUE_MAXVALUE */